version: '3.8'

services:
  postgres-master:
    image: postgres:14
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
      POSTGRES_INITDB_ARGS: "--data-checksums"
      REPLICATOR_PASSWORD: replicator
    ports:
      - "5432:5432"
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
      - ./wrdb-service/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d demo -c 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  postgres-slave:
    image: postgres:14
    container_name: postgres-slave
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PRIMARY_HOST: postgres-master
      PRIMARY_PORT: 5432
      REPLICATOR_PASSWORD: replicator
    ports:
      - "5433:5432"
    volumes:
      - postgres-slave-data:/var/lib/postgresql/data
      - ./wrdb-service/init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
    networks:
      - postgres-network
    depends_on:
      postgres-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -c 'SELECT pg_is_in_recovery();'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  pgpool:
    image: bitnami/pgpool:latest
    container_name: pgpool
    ports:
      - "9999:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres-master:5432,1:postgres-slave:5432
      - PGPOOL_SR_CHECK_PERIOD=10
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
      - PGPOOL_LOAD_BALANCE_MODE=on
      - PGPOOL_MASTER_SLAVE_MODE=on
      - PGPOOL_MASTER_SLAVE_SUB_MODE=stream
      - PGPOOL_HEALTH_CHECK_PERIOD=10
      - PGPOOL_HEALTH_CHECK_USER=postgres
      - PGPOOL_HEALTH_CHECK_PASSWORD=postgres
      - PGPOOL_HEALTH_CHECK_MAX_RETRIES=3
      - PGPOOL_BACKEND_APPLICATION_NAMES=master,slave
    networks:
      - postgres-network
    depends_on:
      postgres-master:
        condition: service_healthy
      postgres-slave:
        condition: service_healthy
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-master-data:
  postgres-slave-data: 